### PR TITLE
Highlighting the missing words in the data

### PR DESCRIPTION
**Pull request by Rahgooy**

### CODE REVIEW

**Comment by MostafaRahgouy** [comment]
Thank you, @Rahgooy. It works very well, especially the color of the ground-truth and model are the same, which is now more visualize! Though, there some minor things I would to sharing.
First thing First, please exchange this line of code in the `helper.js script`. 
#### if (lines[l] == "") 
To:
#### if (lines[l].split("\t").length == 1)   
Also, I think it will be more visualize if we have a more visualize tag(label) for missing words. I mean, when I ran the code, I realized for missing words, the code doesn't highlit them. But I think if we have `Strikethrough` them will be more visual.

**Comment by Rahgooy** [comment]
Thank you for the feedback. It has StrikeThrough, did you generate the missing words file properly?

**Comment by MostafaRahgouy** [comment]
> Thank you for the feedback. It has StrikeThrough, did you generate the missing words file properly?

does the format of the missing words matter? because the format of my missing words is .txt

**Comment by Rahgooy** [comment]
> Thank you, @Rahgooy. It works very well, especially the color of the ground-truth and model are the same, which is now more visualize! Though, there some minor things I would to sharing.
> First thing First, please exchange this line of code in the `helper.js script`.
> 
> #### if (lines[l] == "")
> To:
> 
> #### if (lines[l].split("\t").length == 1)
> Also, I think it will be more visualize if we have a more visualize tag(label) for missing words. I mean, when I ran the code, I realized for missing words, the code doesn't highlit them. But I think if we have `Strikethrough` them will be more visual.

Done!

**Comment by MostafaRahgouy** [comment]
> > Thank you, @Rahgooy. It works very well, especially the color of the ground-truth and model are the same, which is now more visualize! Though, there some minor things I would to sharing.
> > First thing First, please exchange this line of code in the `helper.js script`.
> > #### if (lines[l] == "")
> > To:
> > #### if (lines[l].split("\t").length == 1)
> > Also, I think it will be more visualize if we have a more visualize tag(label) for missing words. I mean, when I ran the code, I realized for missing words, the code doesn't highlit them. But I think if we have `Strikethrough` them will be more visual.
> 
> Done!

Thanks!

**Pull request merged**
