### PR TITLE
initial data visualization 

### PR DESCRIPTION
**Pull request by MostafaRahgouy**
We just used pie and scatter for visualization. We will add more useful data visualizations.
About scatter plot, we didn't find a more precise range for probability, thus, some words are not recognizable on the scatter plot.

### CODE REVIEW

**Comment by Rahgooy** [comment]
Nice job!
You used the max prob to choose the most probable bold word. Please, add another chart where you count the number of bolds in the annotations. For example, if life is annotated as `BOOBOBOOO` you add three, to its frequencies.

**Comment by MostafaRahgouy** [comment]
> Nice job!
> You used the max prob to choose the most probable bold word. Please, add another chart where you count the number of bolds in the annotations. For example, if life is annotated as `BOOBOBOOO` you add three, to its frequencies.

We added the new scatter plot to data visualization as you requested.

**Comment by Rahgooy** [comment]
Why not probability as the previous one? It is not clear what 1000 means for 'best'.  Could you please report with probs?

**Comment by Rahgooy** [comment]
Another thing that could be useful to know is what are the probabilities of being bold given each POS tag.

**Comment by MostafaRahgouy** [comment]
> Another thing that could be useful to know is what are the probabilities of being bold given each POS tag.

**Comment by MostafaRahgouy** [comment]
> Why not probability as the previous one? It is not clear what 1000 means for 'best'. Could you please report with probs?

we did it!!

**Comment by Rahgooy** [comment]
Thanks, looks great!

**Comment by MostafaRahgouy** [comment]
> > Another thing that could be useful to know is what are the probabilities of being bold given each POS tag.

I got it.

**Comment by MostafaRahgouy** [comment]
> Thanks, looks great!

you're most welcome.

**Comment by Rahgooy** [comment]
Some of these words have really high probability of being bold. So, I guess the simple model of just using the probs, should give us a decent result.

**Comment by MostafaRahgouy** [comment]
> Some of these words have really high probability of being bold. So, I guess the simple model of just using the probs, should give us a decent result.

We did it. is it cool?

**Comment by Rahgooy** [comment]
Interesting, NN on average 50% of times becomes bold!

**Comment by Rahgooy** [comment]
I'll merge this, thanks for the hard work.

**Comment by HamedBabaei** [comment]
> I'll merge this, thanks for the hard work.

Thank you

**Comment by HamedBabaei** [comment]
> Interesting, NN on average 50% of times becomes bold!

yes It was so interesting, we hope to get more insight about data in the future experiments!

**Pull request merged**
