### PR TITLE
Help dev

### PR DESCRIPTION
**Pull request by MostafaRahgouy**

### CODE REVIEW

**Comment by Rahgooy** [comment]
Looks good!
Just you need to remove the `__pycache__` and `.vscode` folders. We don't need them.

**Comment by MostafaRahgouy** [comment]
> Looks good!
> Just you need to remove the `__pycache__` and `.vscode` folders. We don't need them.

I removed them sever times but they appeared again

**Comment by Rahgooy** [comment]
Let me know when you have time to do it together

**Comment by MostafaRahgouy** [comment]
> Let me know when you have time to do it together

Sure!

**Comment by Rahgooy** [comment]
Looks great now!
Mereged

**Pull request merged**
