### PR TITLE
Error analysis

### PR DESCRIPTION
**Pull request by Rahgooy**
@MostafaRahgouy , @HamedBabaei Please have a look and let me know what do you think.

### CODE REVIEW

**Comment by Rahgooy** [comment]
@MostafaRahgouy could you please add a function that accepts the vocab and the test data and returns the ids of words that are not in the vocab? Then use this function when you evaluate a model to save the list of the ids in a file. I will use this file in the error analysis tool.
Thanks

**Comment by MostafaRahgouy** [comment]
> @MostafaRahgouy could you please add a function that accepts the vocab and the test data and returns the ids of words that are not in the vocab? Then use this function when you evaluate a model to save the list of the ids in a file. I will use this file in the error analysis tool.
> Thanks

Could you tell us where we have to put this function exactly, please?

**Comment by MostafaRahgouy** [comment]
> @MostafaRahgouy, @HamedBabaei Please have a look and let me know what do you think.

During my examination, the most noticeable thing was related to the words which have zero probability. I mean, in some cases, our model gets a non-zero probability to some words which they have zero probability and vice versa. Take `"Winter Clearance"` as an example. In this instance, our model gives zero to "clearance", whereas, the actual probability of this word is pretty high! Here's, another example `"trees that grow at home"`. the probability of `"grow`" is very high but our models assigned zero to the given word. But in other areas, the model works very well. However, more examinations are needed, but, I think we could focus on this specific error type. Nevertheless, it will be awesome, if we will be able to see all the words which follow this type of error at a single screen with their pos.

**Comment by Rahgooy** [comment]
> > @MostafaRahgouy could you please add a function that accepts the vocab and the test data and returns the ids of words that are not in the vocab? Then use this function when you evaluate a model to save the list of the ids in a file. I will use this file in the error analysis tool.
> > Thanks
> 
> Could you tell us where we have to put this function exactly, please?

Is `build_vocabs` a good place?

**Comment by Rahgooy** [comment]
> > @MostafaRahgouy, @HamedBabaei Please have a look and let me know what do you think.
> 
> During my examination, the most noticeable thing was related to the words which have zero probability. I mean, in some cases, our model gets a non-zero probability to some words which they have zero probability and vice versa. Take `"Winter Clearance"` as an example. In this instance, our model gives zero to "clearance", whereas, the actual probability of this word is pretty high! Here's, another example `"trees that grow at home"`. the probability of `"grow`" is very high but our models assigned zero to the given word. But in other areas, the model works very well. However, more examinations are needed, but, I think we could focus on this specific error type. Nevertheless, it will be awesome, if we will be able to see all the words which follow this type of error at a single screen with their pos.

Good point. That's why I want to add this feature. It will be useful to see what is the performance only on the words were present in the training data.

**Comment by Rahgooy** [comment]
I merge this, to have everything synced for now.

**Pull request merged**
